version:  '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: backend
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh ../scripts/run.sh'
    volumes:
      - ./backend:/backend

  volumes:
    postgres:

